"""Added emotion_values

Revision ID: 8927ffa2e44b
Revises: '0003_replace_messages_column'
Create Date: 2026-08-28 17:23:00.656978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8927ffa2e44b'
down_revision: Union[str, None] = '0003_replace_messages_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'game_data',
        sa.Column(
            'emotion_values',
            sa.JSON(),
            server_default='{"trust": 0.5, "interest": 0.5, "stress": 0.5, "confidence": 0.5, "perceived_risk": 0.5, "sense_of_control": 0.5, "fairness": 0.5}',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_data', 'emotion_values')
    # ### end Alembic commands ###

